var supportsTtf = (function( win ){
    if( !( "FontFace" in win ) ) {
        return false;
    }

    var f = new FontFace('t', 'url( "data:application/font-sfnt;base64,AAEAAAAKAIAAAwAgT1MvMgSkBEEAAACsAAAATmNtYXAADABzAAAA/AAAACxnbHlmCAE5AgAAASgAAAAUaGVhZA5HZ9IAAAE8AAAANmhoZWEIAQQDAAABdAAAACRobXR4BAAAAAAAAZgAAAAIbG9jYQAKAAAAAAGgAAAABm1heHAABAACAAABqAAAACBuYW1lACMIXgAAAcgAAAAgcG9zdAADAAAAAAHoAAAAIAAAAAAAZAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABABAAAAAAABAAAAAAAAAAAAQADAAEAAAAMAAQAIAAAAAQABAABAAAAQP//AAAAQP///8EAAQAAAAAAAQAAAAAEAAQAAAEAADEBBAAEAAABAAAAAQAAVz05718PPPUIAgQAAAAAANBme+sAAAAA0sum8gAAAAAEAAQAAAAAAAACAAAAAAAAAAEAAAQAAAAAAAQAAAAAAAQAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAQAAAAAAAAAAAoAAAABAAAAAgACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAeAAMAAQQJAAEAAgAAAAMAAQQJAAIAAgAAAEAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==" ) format( "truetype" )', {});
    f.load()['catch'](function() {});

    return f.status == 'loading' || f.status == 'loaded';
})( this );
